# -*- coding: utf-8 -*-
"""sort_list_items.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFXJeRpkAXkrYItTDP0hadP5NWhDxgTd
"""

def sortL(L):
  M=[]
  for i in range(len(L)):

    M.append(''.join(sorted(L[i])))
  return M

def stringAnagram(dictionary, query):
  D=sortL(dictionary)
  Q=sortL(query)      
  K=[]
  for i in range(len(Q)):
      c=0
      for j in range(len(D)):
          if Q[i]==D[j]:
              c+=1
      K.append(c)
      c=0
  return K
dictionary=['heater','cold','clod','reheat','docl']
query=['codl','heater','abcd']
stringAnagram(dictionary,query)

